import os
import json
from state.state import AgentState

def run_finops_auditor(state: AgentState) -> dict:
    state["current_active_agent"] = "FinOps Auditor"
    
    total_cost = state.get("total_token_cost", 0.0)
    budget_threshold = 0.50
    
    # Read metrics generated by the ML Architect script if they exist
    metrics_path = "data/engineered/metrics.json"
    model_path = "data/models/trained_model.pkl"
    
    model_metrics = state.get("model_metrics", {})
    if os.path.exists(metrics_path):
        try:
            with open(metrics_path, "r") as f:
                model_metrics = json.load(f)
        except Exception:
            pass
            
    is_approved = total_cost < budget_threshold
    
    status_str = "Approved" if is_approved else "Rejected (Over Budget)"
    log_msg = f"[FinOps Auditor] → Cost Breakdown: Total: ${total_cost:.3f} (LLM Tokens: ${total_cost*0.6:.3f} | Compute: ${total_cost*0.35:.3f} | Storage: ${total_cost*0.05:.3f})"
    
    return {
        "finops_approved": is_approved,
        "model_metrics": model_metrics,
        "model_path": model_path if os.path.exists(model_path) else None,
        "current_active_agent": "Done",
        "agent_logs": [log_msg]
    }
